version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx-proxy:
    image: nginx:alpine
    hostname: nginx-proxy
    restart: always
    ports:
      - "80:80"       # HTTP
      # - "443:443"     # HTTPS
      # - "9200:9200"   # Elasticsearch
      # - "55000:55000" # Wazuh API
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - wazuh-dashboard
      - wazuh-manager
      - wazuh-indexer
    networks:
      - wazuh-network

  # Wazuh Manager
  wazuh.manager:
    image: wazuh/wazuh-manager:4.12.0
    hostname: wazuh.manager
    restart: always
    networks:
      - wazuh-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.12.0
    hostname: wazuh.indexer
    networks:
      - wazuh-network
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.12.0
    hostname: wazuh.dashboard
    restart: always
    networks:
      - wazuh-network
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    hostname: filebeat
    restart: always
    user: root
    command: ["--strict.perms=false"]
    volumes:
      - ./logs:/var/log/custom_logs:ro
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - nginx_logs:/var/log/nginx:ro
      - filebeat_data:/usr/share/filebeat/data
      - filebeat-data:/usr/share/filebeat/data
      - ./custodian-output:/custodian-output:ro
      - wazuh_data:/var/ossec:ro 
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./certs/root-ca.pem:/etc/ssl/root-ca.pem:ro
      - ./certs/filebeat.pem:/etc/ssl/filebeat.pem:ro
      - ./certs/filebeat.key:/etc/ssl/filebeat.key:ro
    environment:
      - ELASTICSEARCH_HOST=wazuh-indexer:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=SecretPassword
    depends_on:
      - wazuh-indexer
    networks:
      - wazuh-network
  cloud-custodian:
    image: cloudcustodian/c7n:latest
    hostname: cloud-custodian
    restart: always
    volumes:
      - ./config/custodian:/home/custodian/policies
      - ./logs/custodian:/home/custodian/logs
      - custodian_cache:/home/custodian/.cache
      - ./aws_credentials:/home/custodian/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - C7N_LOG_LEVEL=INFO
    working_dir: /home/custodian
    command: >
      sh -c "
        echo 'Starting Cloud Custodian scheduler...' &&
        while true; do
          echo 'Running policy validation...' &&
          custodian validate /home/custodian/policies/*.yml &&
          echo 'Running policies...' &&
          custodian run /home/custodian/policies/*.yml --output-dir /home/custodian/logs &&
          echo 'Waiting 1 hour before next run...' &&
          sleep 3600
        done
      "
    networks:
      - wazuh-network

  # Log aggregator for centralized logging
  rsyslog:
    image: rsyslog/rsyslog_base_ubuntu:8.2001.0-ubuntu20.04.1
    hostname: rsyslog-server
    restart: always
    ports:
      - "515:514/udp"   # Changed to avoid conflict with wazuh-manager
      - "515:514/tcp"
    volumes:
      - ./config/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - rsyslog_logs:/var/log
    networks:
      - wazuh-network

volumes:
  wazuh_data:

  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  filebeat_data:
  wazuh-indexer-data:
  custodian_cache:
  nginx_logs:
  rsyslog_logs:
  filebeat-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:

networks:
  wazuh-network:
    driver: bridge