admin:
  hash: "$2a$12$VcCDjrjFkMHmKm4lzWbqjOA9LfKsrQnowkGz/4A1MfWNt7TQ.1HJy"
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"

kibanaserver:
  hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
  reserved: true
  description: "Demo kibanaserver user"